### ISSUE TITLE
Not able to run meteor as suggested in read me doc

### ISSUE THREAD

**Issue by hrath2015** [clinical-meteor/cookbook#94]
command `meteor run --release clinical:METEOR` give error message

**Meteor clinical:METEOR: unknown release.**

**Comment by cdolek** [comment]
@hrath2015 you can use the clinical:METEOR release you have installed:

    $: meteor create hellohealth --release clinical:METEOR@1.3.1-rc14
    $: cd hellohealth
    $: meteor run --release clinical:METEOR@1.3.1-rc14

**Comment by hrath2015** [comment]
Thanks for reply.  Where to get the  clinical:METEOR release. I could not find it  on meteor official repo. tried the url. **https://github.com/meteor/meteor/releases?after=release%2FMETEOR%401.3.2-rc.5**  
DO I need to pull from forked repo.
Sorry for the trouble.

**Comment by cdolek** [comment]
Listen to this to get a better understanding of what clinical-meteor track is:
http://www.meteorinterviews.com/10

**Comment by hrath2015** [comment]
thanks it was helpful Appreciate it.
